### PR TITLE
Fix Segwit Signature check by adding floData length

### PR DESCRIPTION
**Pull request by OstlerDev**
This fixes segwit signature checking by properly initializing a buffer with the correct size to hold the included floData of the transaction. That buffer is then hashed and verified. Because the floData size was not being added to the buffer, it was overflowing when that data was added. This change fixes that bug and allows SegWit transactions to be properly verified if they are signed with their floData.

### CODE REVIEW

**Review by cchrysostom — APPROVED** [review]
Change from MLG. Yep, it looks like fcoin didn't include floData in the tx size.

**Comment by bitspill** [comment]
Looks good for fixing segwit in general.

Is it known what was different about this specific transaction that it stalled now, there have been other segwit transactions in the past which did not fail validation, do those still pass after this patch?

**Comment by OstlerDev** [comment]
@bitspill I believe older SegWit transactions might have omitted the floData in the signature all together possibly. Or, maybe the old transactions happened before the latest checkpoint and weren't being validated previously.

I can perform a full sync of `fcoin` livenet to make sure all of our transactions verify properly though.

**Comment by bitspill** [comment]
@OstlerDev From memory I believe all segwit contain flodata it's more likely the checkpoint as you mention probably they were broken previously but simply not checked. I think we can merge this now to get the explorers back online and if a full sync hangs in the past somewhere start a new PR to resolve that separately

**Review by bitspill — APPROVED** [review]

**Comment by metacoin** [comment]
Looks good. I'd like to check this line out to qualify whether or not it covers all cases: https://github.com/oipwg/fcoin/pull/12/files#diff-0581acfe140526ded4cc6a4ea476809dR724

but I can't think of a reason why it wouldn't off the top of my head

**Pull request merged**
